global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts go to PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    
    # Canary alerts for rapid response
    - match:
        component: canary
      receiver: 'canary-alerts'
      group_wait: 0s
      group_interval: 30s
      repeat_interval: 1h
    
    # Warning alerts to Slack only
    - match:
        severity: warning
      receiver: 'warning-alerts'

# Inhibition rules
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'default'
    slack_configs:
      - channel: '#ybuilt-alerts'
        title: 'YBUILT Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}'
        send_resolved: true

  - name: 'critical-alerts'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
        details:
          firing: '{{ .Alerts.Firing | len }}'
          resolved: '{{ .Alerts.Resolved | len }}'
    slack_configs:
      - channel: '#ybuilt-critical'
        title: ':rotating_light: CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}*{{ .Annotations.summary }}*\n{{ .Annotations.description }}\n{{ .Annotations.runbook }}\n{{ end }}'
        send_resolved: true
        color: 'danger'

  - name: 'canary-alerts'
    slack_configs:
      - channel: '#ybuilt-deployments'
        title: ':warning: Canary Issue: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\nRunbook: {{ .Annotations.runbook }}\n{{ end }}'
        send_resolved: true
        color: 'warning'

  - name: 'warning-alerts'
    slack_configs:
      - channel: '#ybuilt-alerts'
        title: ':warning: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}'
        send_resolved: true
        color: 'warning'
