set -euo pipefail
git ls-files \
  "server/sup/*" \
  "server/mw/sup.ts" \
  "server/mw/pii-scrub.ts" \
  "server/middleware/quotas.ts" \
  "server/metrics/outcome.ts" \
  "server/metrics/*sup*.ts" \
  "server/sup/metrics.*.ts" \
  "server/qa/layout.*.ts" \
  "server/qa/readability.guard.ts" \
  "server/qa/locale.layout.policy.ts" \
  "server/qa/device.*.ts" \
  "server/qa/snapshots*.ts" \
  "server/qa/layout.sup-gate.ts" \
  "server/qa/layout.guardrail.ts" \
  "server/qa/layout.gate.ts" \
  "server/qa/layout.lqr.ts" \
  "server/qa/failure.playbook.ts" \
  "server/qa/edit.search.ts" \
  "server/intent/router.brain.ts" \
  "server/intent/citelock*.ts" \
  "server/perf/budgets.ts" \
  "server/tenancy/workspace*.ts" \
  "server/mw/abuse.mesh.ts" \
  "server/ai/router.ts" \
  "server/ai/router.compose.ts" \
  "server/ai/router.metrics.ts" \
  "server/ai/router.review.ts" \
  "tests/sup.*.spec.ts" \
  "tests/mw.sup.spec.ts" \
  "tests/mw.pii-scrub.spec.ts" \
  "tests/abuse.mesh.spec.ts" \
  "tests/layout.*.spec.ts" \
  "tests/readability.guard.spec.ts" \
  "tests/locale.layout.policy.spec.ts" \
  "tests/device.sanity.spec.ts" \
  "tests/snapshots.diff.spec.ts" \
  "tests/metrics.outcome.spec.ts" \
  "tests/sup.metrics.*.spec.ts" \
  "tests/workspace.*.spec.ts" \
  "tests/perf.budgets.spec.ts" \
  "tests/part1-core.spec.ts" \
  "tests/part3-compose.spec.ts" \
  "tests/part5-metrics.spec.ts" \
  "tests/e2e.golden.spec.ts" \
  2>/dev/null | sort -u
