name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Run QA tests
        env:
          TEST_PORT: 5001
          NODE_ENV: test
          LOG_LEVEL: INFO
          RAZORPAY_MODE: mock
        run: |
          node test/run-all-tests.cjs
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            test/**/*.log
            data/**/*.log
            *.log
          retention-days: 7
